<?php

return [
    'absolute_path' => $_SERVER['DOCUMENT_ROOT'],
    'frontend_path' => $_SERVER['DOCUMENT_ROOT'].'/iipars/ugcnet/public/frontend/', 
    'assets_path' => $_SERVER['DOCUMENT_ROOT'].'/iipars/ugcnet/public',
    'main_site_path' => '/',
    'user_image' => $_SERVER['DOCUMENT_ROOT'].'/iipars/ugcnet/public/uploads/user_image/',
    'material_image' => 'storage/uploads/materials/',
    'partner_image' => $_SERVER['DOCUMENT_ROOT'].'/iipars/ugcnet/public/uploads/partner_image/',
    'portfolio_image' => $_SERVER['DOCUMENT_ROOT'].'/iipars/ugcnet/public/uploads/portfolio_image/',
    'hotel_image' => $_SERVER['DOCUMENT_ROOT'].'/iipars/ugcnet/public/uploads/hotel_image/',
    'banner_image' => $_SERVER['DOCUMENT_ROOT'].'/iipars/ugcnet/public/uploads/banner_image/',
    'project_image' => $_SERVER['DOCUMENT_ROOT'].'/iipars/ugcnet/public/uploads/project_image/',
    'blog_image' => $_SERVER['DOCUMENT_ROOT'].'/iipars/ugcnet/public/uploads/blog_image/',
    'cms_image' => $_SERVER['DOCUMENT_ROOT'].'/iipars/ugcnet/public/uploads/cms_image/',
    'cms_banner_image' => $_SERVER['DOCUMENT_ROOT'].'/iipars/ugcnet/public/uploads/cms_image/banner_image/',
    'request_quote' => $_SERVER['DOCUMENT_ROOT'].'/iipars/ugcnet/public/uploads/request_quote/',
    'wc_icon_path' => $_SERVER['DOCUMENT_ROOT'].'/iipars/ugcnet/public/uploads/category_images/',
    'speaker_image_path' => $_SERVER['DOCUMENT_ROOT'].'/iipars/ugcnet/public/uploads/speaker_images/',
    'how_it_work_image_path' => $_SERVER['DOCUMENT_ROOT'].'/iipars/ugcnet/public/uploads/how_it_work_images/',
    'project_attachment' => $_SERVER['DOCUMENT_ROOT'].'/iipars/ugcnet/public/uploads/project_attachment/',
    'resume_path' => $_SERVER['DOCUMENT_ROOT'].'/iipars/ugcnet/public/uploads/resume/',
    'work_file' => $_SERVER['DOCUMENT_ROOT'].'/iipars/ugcnet/public/uploads/work_file/',
    'proposal_file' => $_SERVER['DOCUMENT_ROOT'].'/iipars/ugcnet/public/uploads/proposal_file/',
    'chat_image' => $_SERVER['DOCUMENT_ROOT'].'/iipars/ugcnet/public/uploads/message_attachment/', 
    'chat_thumbnails' => $_SERVER['DOCUMENT_ROOT'].'/iipars/ugcnet/public/uploads/message_attachment/thumbnails/', 
    'id_proof' => $_SERVER['DOCUMENT_ROOT'].'/iipars/ugcnet/public/uploads/id_proof/',
    'police_report' => $_SERVER['DOCUMENT_ROOT'].'/iipars/ugcnet/public/uploads/police_report/',
    'address_proof' => $_SERVER['DOCUMENT_ROOT'].'/iipars/ugcnet/public/uploads/address_proof/',
    'course_image' => 'storage/uploads/courses/',
];